[package]
name = "http-wasm-rust"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http-wasm-guest = { path = "../http-wasm-guest" }