name: Release

on:
  push:
    tags:
        - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-wasip1
    - name: Build
      run: make plugin
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: plugin/**
      
      
