name: Release

on:
  push:
    tags:
        - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-wasip1
    - name: Build
      run: make plugin
    - name: Release
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: plugin/**
        include-hidden-files: true

      
